
erver:
  port: 8080
spring:
  fastjson:
    enabled: true
    supported-media-types: application/json;charset=UTF-8
    config:
      date-format: yyyy-MM-dd HH:mm:ss
      charset: UTF-8
      serializer-features:
        - prettyformat
        - writemapnullvalue
        - writenullnumberaszero
        - writenullstringasempty
        - writenulllistasempty
memcached:
  socket-addresses:
    -
      hostname: 192.168.0.100
      port: 12000
    -
      hostname: 192.168.0.101
      port: 12000
  weights: # 分布式权重
    - 1
    - 1
